CREATE TABLE change_order (
  id DATE PRIMARY KEY,
  quarters NUMERIC NOT NULL,
  dimes NUMERIC NOT NULL,
  nickles NUMERIC NOT NULL,
  pennies NUMERIC NOT NULL,
  ones NUMERIC NOT NULL,
  fives NUMERIC NOT NULL
);